# /etc/opendkim.conf  – nur Challenges/Bestaetigungen signieren
Syslog                  yes
SyslogSuccess           yes
UMask                   007
Mode                    sv
Socket                  inet:8891@localhost
PidFile                 /run/opendkim/opendkim.pid
UserID                  opendkim

Canonicalization        relaxed/simple
OversignHeaders         From
SubDomains              no

KeyTable                file:/etc/dkimkeys/key.table
SigningTable            refile:/etc/dkimkeys/signing.table
InternalHosts           refile:/etc/dkimkeys/trusted.hosts
